Repository ros-infrastructure/catkin_pkg, pull requests merged in 2020-05, with the labels that each got.

#286 Respect (AMENT|COLCON|CATKIN)_IGNORE directories
  src/catkin_pkg/packages.py
Labels: question

#287 Restore compatibility with pyparsing < 1.5.7
  setup.py
  src/catkin_pkg/condition.py
Labels: bug

#292 add GitLab auto linking for issues in catkin_generate_changelog
  src/catkin_pkg/changelog_generator_vcs.py
Labels: enhancement
